[build]
  command = "npm run build"
  publish = "dist/spaportfolio/browser"

[dev]
  command = "npm run start"
  port = 4200
  targetPort = 5000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/json-server"
  status = 200